### ISSUE TITLE
Finishing Text Classification Model

### ISSUE THREAD

**Issue by hmc-cs-mstreinz** [andrewlew1s/hmc-transcribers#12]
@ievans-HMC Here are some tasks regarding your model, I organized them in relative importance.

- [x] Finish training text classification model
- [x] Test model on inputs of a variety of lengths and with duplicates in the sentence
- [x] Notify me and Lavon as soon as it's ready
- [x] Create a spreadsheet of your model's performance by field

**Comment by ievans-HMC** [comment]
Current status with model:

Category | Accuracy
---------------|---------------------
city | accuracy: 0.6237
country | accuracy: 0.9250
email_id | accuracy: 0.2763
fax | accuracy: 0.1296
first_name | accuracy: 0.7434
last_name | accuracy: 0.7636
office_address | accuracy: 0.5049
office_address2 | accuracy: 0.3421
phone | accuracy: 0.2698
state | accuracy: 0.7857
title | accuracy: 0.6593
zipcode | accuracy: 0.2091
